[context.master]
  [context.master.environment]
    REACT_APP_API_URL = 'https://analytics-node-server-prod-7ozakeh7pa-nw.a.run.app'
    REACT_APP_AUTH0_CLIENT_ID = 'LRLESqjJ9Hmoarbzg7sj4Jbj4NFARRvb'
    REACT_APP_AUTH0_DOMAIN = 'wealth8-admin.eu.auth0.com'

[context.dev]
  [context.dev.environment]
    REACT_APP_API_URL = 'https://analytics-node-server-staging-esbvxjgvda-uc.a.run.app'
    REACT_APP_AUTH0_CLIENT_ID = 'LRLESqjJ9Hmoarbzg7sj4Jbj4NFARRvb'
    REACT_APP_AUTH0_DOMAIN = 'wealth8-admin.eu.auth0.com'

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
